# Which is equivalent to
# format = '$all$directory$character'
add_newline = true

format = """$directory$character"""

right_format = "$hostname$git_branch$time"

[character]
success_symbol = '[âžœ](bold green)'

[gcloud]
